Add and modify module files to compile GSI-utils on AWS
NOAA-EMC/GSI-utils pull request #37
Opened 2024-04-25 16:39 UTC by weihuang-jedi

Add and modify module files to compile GSI-utils on AWS and other NOAA Cloud platforms. This PR is for issue: #36 

https://github.com/NOAA-EMC/GSI-utils/issues/36

2024-04-25 16:55 UTC, aerorahul requested changes
Some comments.

2024-04-25 16:55 UTC, aerorahul commented on modulefiles/gsiutils_noaacloud.intel.lua
> +load("bufr/11.7.0")
```suggestion
```
`bufr/11.7.0` is loaded in `gsiutils_common`.

2024-04-25 16:55 UTC, aerorahul commented on modulefiles/gsiutils_noaacloud.intel.lua
> +local python_ver=os.getenv("python_ver") or "3.11.6"
This is misplaced. `python_ver` is used on line 15.
Also, spack-stack provides python, and this should be `stack_python_ver`.  Please see https://github.com/NOAA-EPIC/GSI-utils-cloud/blob/7393ec2c9935a12af600456162d5cba1ca020b63/modulefiles/gsiutils_hercules.intel.lua#L6
Declaring `python_ver` after `python` is loaded is not useful.

2024-04-25 17:28 UTC, weihuang-jedi commented on modulefiles/gsiutils_noaacloud.intel.lua
> +local python_ver=os.getenv("python_ver") or "3.11.6"
rename and reordered.

2024-04-25 17:30 UTC, weihuang-jedi commented on modulefiles/gsiutils_noaacloud.intel.lua
> +load("bufr/11.7.0")
Now removed this line

2024-04-26 18:52 UTC, aerorahul approved these changes
looks good.

2024-04-26 19:41 UTC, merged